import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

const sessionValidator = v.object({
  goal: v.string(),
  break_minutes: v.number(),
  status: v.string(),
  attempts: v.number(),
  job_id: v.optional(v.id("jobs")),
  started_at: v.optional(v.number()),
  ended_at: v.optional(v.number()),
});

const DEFAULT_CAPS = { comments: 10, likes: 40, dms: 5, follows: 10 };

/** Create a draft plan (generated by the backend planner, reviewed by the user). */
export const createPlan = mutation({
  args: {
    user_id: v.string(),
    raw_goal: v.string(),
    sessions: v.array(v.object({ goal: v.string(), break_minutes: v.number() })),
    daily_caps: v.optional(
      v.object({
        comments: v.number(),
        likes: v.number(),
        dms: v.number(),
        follows: v.number(),
      })
    ),
  },
  handler: async (ctx, { user_id, raw_goal, sessions, daily_caps }) => {
    // Only one active plan per user — supersede any old draft.
    for (const status of ["draft", "running"]) {
      const existing = await ctx.db
        .query("day_plans")
        .withIndex("by_user_status", (q) => q.eq("user_id", user_id).eq("status", status))
        .collect();
      for (const row of existing) {
        await ctx.db.patch(row._id, { status: "cancelled", ended_at: Date.now() });
      }
    }

    return await ctx.db.insert("day_plans", {
      user_id,
      raw_goal,
      status: "draft",
      sessions: sessions.map((s) => ({
        goal: s.goal,
        break_minutes: s.break_minutes,
        status: "pending",
        attempts: 0,
      })),
      current_index: 0,
      daily_caps: daily_caps ?? DEFAULT_CAPS,
      created_at: Date.now(),
    });
  },
});

/** The user's current plan (draft or running), newest first. */
export const activePlan = query({
  args: { user_id: v.string() },
  handler: async (ctx, { user_id }) => {
    const identity = await ctx.auth.getUserIdentity();
    const uid = identity?.subject ?? user_id;
    for (const status of ["running", "draft"]) {
      const rows = await ctx.db
        .query("day_plans")
        .withIndex("by_user_status", (q) => q.eq("user_id", uid).eq("status", status))
        .order("desc")
        .take(1);
      if (rows.length) return rows[0];
    }
    return null;
  },
});

/** Recent finished plans, for history. */
export const recentPlans = query({
  args: { user_id: v.string(), limit: v.optional(v.number()) },
  handler: async (ctx, { user_id, limit }) => {
    const identity = await ctx.auth.getUserIdentity();
    const uid = identity?.subject ?? user_id;
    const all = await ctx.db.query("day_plans").order("desc").take(50);
    return all.filter((p) => p.user_id === uid).slice(0, limit ?? 10);
  },
});

/** Replace the session list while the plan is still a draft (dashboard editing). */
export const updateSessions = mutation({
  args: {
    plan_id: v.id("day_plans"),
    sessions: v.array(v.object({ goal: v.string(), break_minutes: v.number() })),
  },
  handler: async (ctx, { plan_id, sessions }) => {
    const plan = await ctx.db.get(plan_id);
    if (!plan || plan.status !== "draft") return;
    await ctx.db.patch(plan_id, {
      sessions: sessions.map((s) => ({
        goal: s.goal,
        break_minutes: s.break_minutes,
        status: "pending",
        attempts: 0,
      })),
    });
  },
});

/** Kick the plan off — the backend poller takes it from here. */
export const startPlan = mutation({
  args: { plan_id: v.id("day_plans") },
  handler: async (ctx, { plan_id }) => {
    const plan = await ctx.db.get(plan_id);
    if (!plan || plan.status !== "draft") return;
    await ctx.db.patch(plan_id, {
      status: "running",
      started_at: Date.now(),
      current_index: 0,
      next_run_at: Date.now(),
    });
  },
});

export const cancelPlan = mutation({
  args: { plan_id: v.id("day_plans"), note: v.optional(v.string()) },
  handler: async (ctx, { plan_id, note }) => {
    await ctx.db.patch(plan_id, {
      status: "cancelled",
      ended_at: Date.now(),
      note: note ?? "Cancelled by user",
    });
  },
});

// ── Backend poller API ───────────────────────────────────────────────────────

/** All running plans — the poller scans these each tick. */
export const runningPlans = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db
      .query("day_plans")
      .withIndex("by_status", (q) => q.eq("status", "running"))
      .collect();
  },
});

/** Mark a session as dispatched to the bot. */
export const markSessionRunning = mutation({
  args: { plan_id: v.id("day_plans"), index: v.number(), job_id: v.optional(v.id("jobs")) },
  handler: async (ctx, { plan_id, index, job_id }) => {
    const plan = await ctx.db.get(plan_id);
    if (!plan) return;
    const sessions = [...plan.sessions];
    if (!sessions[index]) return;
    sessions[index] = {
      ...sessions[index],
      status: "running",
      attempts: sessions[index].attempts + 1,
      job_id,
      started_at: Date.now(),
    };
    await ctx.db.patch(plan_id, { sessions, next_run_at: undefined });
  },
});

/** Session finished: advance to the next one after its break, or retry it. */
export const finishSession = mutation({
  args: {
    plan_id: v.id("day_plans"),
    index: v.number(),
    outcome: v.string(),        // "done" | "error"
    retry: v.boolean(),         // true => re-run this same session shortly
    retry_delay_seconds: v.optional(v.number()),
  },
  handler: async (ctx, { plan_id, index, outcome, retry, retry_delay_seconds }) => {
    const plan = await ctx.db.get(plan_id);
    if (!plan) return;
    const sessions = [...plan.sessions];
    if (!sessions[index]) return;

    if (retry) {
      sessions[index] = { ...sessions[index], status: "pending" };
      await ctx.db.patch(plan_id, {
        sessions,
        next_run_at: Date.now() + (retry_delay_seconds ?? 60) * 1000,
      });
      return;
    }

    sessions[index] = { ...sessions[index], status: outcome, ended_at: Date.now() };
    const nextIndex = index + 1;

    if (nextIndex >= sessions.length) {
      await ctx.db.patch(plan_id, {
        sessions,
        current_index: nextIndex,
        status: "done",
        ended_at: Date.now(),
        next_run_at: undefined,
      });
      return;
    }

    const breakMs = (sessions[index].break_minutes ?? 0) * 60 * 1000;
    await ctx.db.patch(plan_id, {
      sessions,
      current_index: nextIndex,
      next_run_at: Date.now() + breakMs,
    });
  },
});

/** Stop a plan early (e.g. daily cap reached). */
export const endPlan = mutation({
  args: { plan_id: v.id("day_plans"), status: v.string(), note: v.optional(v.string()) },
  handler: async (ctx, { plan_id, status, note }) => {
    await ctx.db.patch(plan_id, { status, ended_at: Date.now(), note, next_run_at: undefined });
  },
});

/** Totals logged today — used to enforce the daily caps. */
export const todayTotals = query({
  args: {},
  handler: async (ctx) => {
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const since = start.getTime();
    const rows = (await ctx.db.query("sessions").collect()).filter(
      (s) => s.started_at >= since
    );
    return rows.reduce(
      (acc, s) => ({
        comments: acc.comments + (s.comments ?? 0),
        likes: acc.likes + (s.likes ?? 0),
        dms: acc.dms + (s.dms ?? 0),
        follows: acc.follows + (s.follows ?? 0),
      }),
      { comments: 0, likes: 0, dms: 0, follows: 0 }
    );
  },
});

/** Job status lookup for the poller (did the dispatched session succeed?). */
export const jobStatus = query({
  args: { job_id: v.id("jobs") },
  handler: async (ctx, { job_id }) => {
    const job = await ctx.db.get(job_id);
    return job ? job.status : null;
  },
});
